### ISSUE TITLE
use mqtt in android device coolpad 5950 android4.1 appear NullPointerException

### ISSUE THREAD

**Issue by wwwjiandan** [fusesource/mqtt-client#39]
java.lang.NullPointerException
	at org.fusesource.mqtt.client.CallbackConnection$7.run(CallbackConnection.java:414)
	at org.fusesource.hawtdispatch.transport.HeartBeatMonitor$3.run(HeartBeatMonitor.java:83)
	at org.fusesource.hawtdispatch.transport.HeartBeatMonitor$1.run(HeartBeatMonitor.java:62)
	at org.fusesource.hawtdispatch.internal.SerialDispatchQueue.run(SerialDispatchQueue.java:100)
	at org.fusesource.hawtdispatch.internal.pool.SimpleThread.run(SimpleThread.java:77)

**Comment by wwwjiandan** [comment]
most NPE appear in Android4.4 OS

**Comment by luchec** [comment]
哥们你解决这个问题了吗，我的问题跟你一样！
