### ISSUE TITLE
Peer Disconnection...

### ISSUE THREAD

**Issue by ansondtx20** [fusesource/mqtt-client#50]
Hi:

I am trying to use the mqtt-client library (v1.11) with IBM IoT Foundations and, for the most part, everything works fine. 

However, after some amount of use (varies...) I start getting the following un-trappable exception:
4: java.io.EOFException: Peer disconnected
	at org.fusesource.hawtdispatch.transport.AbstractProtocolCodec.read(AbstractProtocolCodec.java:331)
	at org.fusesource.hawtdispatch.transport.TcpTransport.drainInbound(TcpTransport.java:706)
	at org.fusesource.hawtdispatch.transport.TcpTransport$6.run(TcpTransport.java:588)
	at org.fusesource.hawtdispatch.internal.NioDispatchSource$3.run(NioDispatchSource.java:209)
	at org.fusesource.hawtdispatch.internal.SerialDispatchQueue.run(SerialDispatchQueue.java:100)
	at org.fusesource.hawtdispatch.internal.pool.SimpleThread.run(SimpleThread.java:77)

I am not sure what this exception implies because of the following:
- the publish() method continues to succeed... it does not return any error condition or exception after the above exception is first seen...
- nothing is making its way into IoT Foundations any more.... as if the publish() does not actually work. 

Has anyone else seen this?  Any ideas what it might be?

Thanks in advance...

Doug

**Comment by yeminkhaung** [comment]
Did you solved the problem?
Otherwise hoping anyone from the team could help this problem...

I am also having the same problem of "peer disconnected" after publish() is succeeded.

**Comment by ansondtx20** [comment]
None yet... trapping the issue for now... may end up switching over to the Paho library.

**Comment by kthacker7** [comment]
Anyone looked into this yet? Running into this issue even now

**Comment by cleverpig** [comment]
mark+1

**Comment by vae13** [comment]
卧槽！我也是这个问题，这是为啥
