### ISSUE TITLE
Repeated connection causes the program to crash

### ISSUE THREAD

**Issue by alafighting** [fusesource/mqtt-client#65]
It looks like this.

> onDisconnected()
> onConnected()
> onConnected()
> onDisconnected()
> E/AndroidRuntime: FATAL EXCEPTION: hawtdispatch-DEFAULT-2
                  Process: com.xxx.xxx, PID: 22875
                  java.lang.NullPointerException: Attempt to invoke interface method 'boolean org.fusesource.hawtdispatch.transport.Transport.offer(java.lang.Object)' on a null object reference
                      at org.fusesource.mqtt.client.CallbackConnection$7.run(CallbackConnection.java:449)
                      at org.fusesource.hawtdispatch.transport.HeartBeatMonitor$3.run(HeartBeatMonitor.java:83)
                      at org.fusesource.hawtdispatch.transport.HeartBeatMonitor$1.run(HeartBeatMonitor.java:62)
                      at org.fusesource.hawtdispatch.internal.SerialDispatchQueue.run(SerialDispatchQueue.java:100)
                      at org.fusesource.hawtdispatch.internal.pool.SimpleThread.run(SimpleThread.java:77)

**Comment by kofokey** [comment]
这个bug你解决了吗

**Comment by kanghaixian** [comment]
how do you deal with it

**Comment by ImKarl** [comment]
I don't know.
I don't do it now.

**Comment by QX-Zach** [comment]
I've had this problem, too.
